{{- if .Values.serviceaccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.serviceaccount.customName }}
  name: {{ .Values.serviceaccount.customName }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.serviceaccount.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}
